version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - .:/home/app:Z
    network_mode: host
    command: /bin/bash /home/app/docker-entrypoint.sh
    environment:
      - DB_HOST=127.0.0.1
